package com.example.redvoznje.stations;

import java.util.ArrayList;

public class StationFillAll {

    private static ArrayList<Station> allStations;

    public static ArrayList<Station> fillAllStation() {
        helperFillAllStation();

        return allStations;
    }

    private static void helperFillAllStation() {
        allStations = new ArrayList<>();

        allStations.add(new Station("Kemendin st", "01016"));
        allStations.add(new Station("Altina st", "01017"));
        allStations.add(new Station("ROESZKE", "04282"));
        allStations.add(new Station("SZEGED", "04905"));
        allStations.add(new Station("JIMBOLIA", "05129"));
        allStations.add(new Station("STAMORA MORAVITA", "06113"));
        allStations.add(new Station("DOLJEVAC", "11001"));
        allStations.add(new Station("KOCANE", "11002"));
        allStations.add(new Station("PUKOVAC", "11003"));
        allStations.add(new Station("BRESTOVAC", "11004"));
        allStations.add(new Station("LIPOVICA", "11005"));
        allStations.add(new Station("PEČENJEVCE", "11006"));
        allStations.add(new Station("ŽIVKOVO", "11007"));
        allStations.add(new Station("PRIBOJ LESKOVAČKI", "11009"));
        allStations.add(new Station("LESKOVAC", "11050"));
        allStations.add(new Station("MATARUŠKA BANJA", "12101"));
        allStations.add(new Station("PROGORELICA", "12102"));
        allStations.add(new Station("BOGUTOVAČKA BANJA", "12103"));
        allStations.add(new Station("POLUMIR", "12105"));
        allStations.add(new Station("UŠĆE", "12106"));
        allStations.add(new Station("JOŠANIČKA BANJA", "12107"));
        allStations.add(new Station("PISKANJA", "12108"));
        allStations.add(new Station("BRVENIK", "12109"));
        allStations.add(new Station("RVATI", "12110"));
        allStations.add(new Station("RAŠKA", "12111"));
        allStations.add(new Station("KAZNOVIĆI", "12112"));
        allStations.add(new Station("RUDNICA", "12113"));
        allStations.add(new Station("LOZNO", "12115"));
        allStations.add(new Station("PUSTO POLJE", "12116"));
        allStations.add(new Station("MRZENICA", "12201"));
        allStations.add(new Station("DEDINA", "12203"));
        allStations.add(new Station("KRUŠEVAC", "12204"));
        allStations.add(new Station("KOŠEVI", "12205"));
        allStations.add(new Station("STOPANJA", "12207"));
        allStations.add(new Station("POCEKOVINA", "12208"));
        allStations.add(new Station("TRSTENIK", "12210"));
        allStations.add(new Station("VRNJAČKA BANJA", "12211"));
        allStations.add(new Station("LIPOVA STA", "12212"));
        allStations.add(new Station("PODUNAVCI", "12213"));
        allStations.add(new Station("VRBA STAJ", "12214"));
        allStations.add(new Station("RATINA", "12215"));
        allStations.add(new Station("TOMINAC STA", "12216"));
        allStations.add(new Station("VRANEŠI STAJ", "12217"));
        allStations.add(new Station("ČITLUK", "12218"));
        allStations.add(new Station("GRAD STALAĆ STA", "12219"));
        allStations.add(new Station("MEĐUROVO", "12301"));
        allStations.add(new Station("BELOTINCE", "12302"));
        allStations.add(new Station("MALOŠIŠTE", "12303"));
        allStations.add(new Station("ČAPLJINAC", "12304"));
        allStations.add(new Station("BRALJINA", "12502"));
        allStations.add(new Station("STARO TRUBAREVO", "12503"));
        allStations.add(new Station("ĐUNIS", "12504"));
        allStations.add(new Station("VITKOVAC STAJ.", "12505"));
        allStations.add(new Station("DONJI LJUBEŠ", "12506"));
        allStations.add(new Station("KORMAN", "12507"));
        allStations.add(new Station("TRNJANI", "12508"));
        allStations.add(new Station("ADROVAC", "12509"));
        allStations.add(new Station("ALEKSINAC", "12510"));
        allStations.add(new Station("LUŽANE", "12511"));
        allStations.add(new Station("TEŠICA", "12512"));
        allStations.add(new Station("GREJAČ", "12513"));
        allStations.add(new Station("SUPOVAČKI MOST", "12514"));
        allStations.add(new Station("MEZGRAJA", "12515"));
        allStations.add(new Station("TRUPALE", "12516"));
        allStations.add(new Station("CEROVO RAŽANJ", "12517"));
        allStations.add(new Station("VRTIŠTE", "12518"));
        allStations.add(new Station("GORNJI LJUBEŠ", "12519"));
        allStations.add(new Station("NOZRINA", "12520"));
        allStations.add(new Station("CRVENI KRST", "12550"));
        allStations.add(new Station("NIŠ", "12551"));
        allStations.add(new Station("ADRANI", "13001"));
        allStations.add(new Station("MRSAĆ", "13002"));
        allStations.add(new Station("SAMAILA", "13003"));
        allStations.add(new Station("GORIČANI", "13004"));
        allStations.add(new Station("MRSINCI", "13005"));
        allStations.add(new Station("ZABLAĆE", "13006"));
        allStations.add(new Station("PRIJEVOR", "13007"));
        allStations.add(new Station("OVČAR BANJA", "13008"));
        allStations.add(new Station("DRAGAČEVO", "13009"));
        allStations.add(new Station("TRBUŠANI", "13010"));
        allStations.add(new Station("BORAČKO", "13011"));
        allStations.add(new Station("BALUGA", "13012"));
        allStations.add(new Station("JELEN DO", "13013"));
        allStations.add(new Station("KUKIĆI", "13014"));
        allStations.add(new Station("GUGALJ STA", "13015"));
        allStations.add(new Station("ČAČAK", "13060"));
        allStations.add(new Station("BATOČINA", "13201"));
        allStations.add(new Station("GRADAC", "13202"));
        allStations.add(new Station("BADNJEVAC", "13203"));
        allStations.add(new Station("RESNIK KRAGUJEVAČKI", "13204"));
        allStations.add(new Station("MILATOVAC", "13205"));
        allStations.add(new Station("JOVANOVAC", "13207"));
        allStations.add(new Station("ZAVOD", "13209"));
        allStations.add(new Station("GROŠNICA", "13210"));
        allStations.add(new Station("DRAGOBRAĆA", "13211"));
        allStations.add(new Station("KNIĆ", "13213"));
        allStations.add(new Station("GRUŽA", "13214"));
        allStations.add(new Station("GUBEREVAC", "13215"));
        allStations.add(new Station("VITKOVAC", "13216"));
        allStations.add(new Station("MILAVČIĆI", "13217"));
        allStations.add(new Station("VITANOVAC", "13218"));
        allStations.add(new Station("ŠUMARICE", "13219"));
        allStations.add(new Station("SIRČA", "13220"));
        allStations.add(new Station("TOMIĆA BRDO", "13221"));
        allStations.add(new Station("KRAGUJEVAC", "13250"));
        allStations.add(new Station("KRALJEVO", "13251"));
        allStations.add(new Station("BRZAN", "13301"));
        allStations.add(new Station("MILOŠEVO", "13302"));
        allStations.add(new Station("BAGRDAN", "13303"));
        allStations.add(new Station("LANIŠTE", "13304"));
        allStations.add(new Station("BUKOVČE", "13305"));
        allStations.add(new Station("GILJE", "13307"));
        allStations.add(new Station("PARAĆIN", "13310"));
        allStations.add(new Station("SIKIRICA-RATARI", "13311"));
        allStations.add(new Station("DRENOVAC", "13312"));
        allStations.add(new Station("ĆIĆEVAC", "13313"));
        allStations.add(new Station("LUČINA", "13314"));
        allStations.add(new Station("JAGODINA", "13350"));
        allStations.add(new Station("ĆUPRIJA", "13351"));
        allStations.add(new Station("STALAĆ", "13352"));
        allStations.add(new Station("VELIKA PLANA", "13401"));
        allStations.add(new Station("STARO SELO", "13402"));
        allStations.add(new Station("NOVO SELO", "13403"));
        allStations.add(new Station("MARKOVAC", "13404"));
        allStations.add(new Station("LAPOVO VAROŠ", "13405"));
        allStations.add(new Station("LAPOVO", "13450"));
        allStations.add(new Station("MALA KRSNA", "13551"));
        allStations.add(new Station("GODOMIN", "13602"));
        allStations.add(new Station("RADINAC", "13603"));
        allStations.add(new Station("VRANOVO", "13604"));
        allStations.add(new Station("SMEDEREVO", "13670"));
        allStations.add(new Station("KOVAČEVAC", "13701"));
        allStations.add(new Station("RABROVAC", "13702"));
        allStations.add(new Station("KUSADAK", "13703"));
        allStations.add(new Station("RATARE", "13704"));
        allStations.add(new Station("GLIBOVAC", "13705"));
        allStations.add(new Station("PALANKA", "13706"));
        allStations.add(new Station("MALA PLANA", "13707"));
        allStations.add(new Station("MATEJEVAC", "14001"));
        allStations.add(new Station("PANTELEJ", "14003"));
        allStations.add(new Station("JASENOVIK", "14004"));
        allStations.add(new Station("GRAMADA", "14005"));
        allStations.add(new Station("HADŽIĆEVO", "14006"));
        allStations.add(new Station("SVRLJIG", "14007"));
        allStations.add(new Station("NIŠEVAC", "14008"));
        allStations.add(new Station("PALILULA", "14009"));
        allStations.add(new Station("SVRLJIŠKI MILJKOVAC", "14010"));
        allStations.add(new Station("PODVIS", "14011"));
        allStations.add(new Station("RGOŠTE", "14012"));
        allStations.add(new Station("KNJAŽEVAC", "14013"));
        allStations.add(new Station("GORNJE ZUNIĆE", "14014"));
        allStations.add(new Station("DONJE ZUNIĆE", "14015"));
        allStations.add(new Station("MINIĆEVO", "14016"));
        allStations.add(new Station("SELAČKA REKA", "14017"));
        allStations.add(new Station("MALI IZVOR", "14018"));
        allStations.add(new Station("VRATARNICA", "14019"));
        allStations.add(new Station("GRLJAN", "14021"));
        allStations.add(new Station("TIMOK", "14022"));
        allStations.add(new Station("SV MILJKOVAC STAJ", "14024"));
        allStations.add(new Station("ZAJEČAR", "14060"));
        allStations.add(new Station("TRNAVAC", "14101"));
        allStations.add(new Station("ČOKONJAR", "14102"));
        allStations.add(new Station("SOKOLOVICA", "14103"));
        allStations.add(new Station("TABAKOVAC", "14104"));
        allStations.add(new Station("TABAKOVAČKA REKA", "14105"));
        allStations.add(new Station("BRUSNIK", "14106"));
        allStations.add(new Station("TAMNIĆ", "14107"));
        allStations.add(new Station("CRNOMASNICA", "14108"));
        allStations.add(new Station("RAJAC", "14109"));
        allStations.add(new Station("ROGLJEVO", "14110"));
        allStations.add(new Station("VELJKOVO", "14111"));
        allStations.add(new Station("KOBIŠNICA", "14113"));
        allStations.add(new Station("NEGOTIN", "14114"));
        allStations.add(new Station("PRAHOVO", "14115"));
        allStations.add(new Station("PRAHOVO PRISTANIŠTE", "14170"));
        allStations.add(new Station("VRAŽOGRNAC", "14301"));
        allStations.add(new Station("RGOTINA", "14302"));
        allStations.add(new Station("ZAGRAĐE", "14303"));
        allStations.add(new Station("BORSKA SLATINA", "14304"));
        allStations.add(new Station("BOR TERETNA", "14305"));
        allStations.add(new Station("BOR", "14350"));
        allStations.add(new Station("MAJDANPEK", "14401"));
        allStations.add(new Station("LESKOVO", "14402"));
        allStations.add(new Station("JASIKOVO", "14403"));
        allStations.add(new Station("VLAOLE", "14404"));
        allStations.add(new Station("CEROVO", "14405"));
        allStations.add(new Station("KRIVELJSKI POTOK", "14406"));
        allStations.add(new Station("MALI KRIVELJ", "14407"));
        allStations.add(new Station("GORNJANE", "14408"));
        allStations.add(new Station("KRIVELJSKI MOST", "14409"));
        allStations.add(new Station("DEBELI LUG", "14410"));
        allStations.add(new Station("VLAOLE SELO", "14411"));
        allStations.add(new Station("ŠUŠULAJKA", "14412"));
        allStations.add(new Station("BREZONIK", "14413"));
        allStations.add(new Station("POŽAREVAC", "14550"));
        allStations.add(new Station("LJUBIČEVSKI MOST", "14551"));
        allStations.add(new Station("LASTRA", "15102"));
        allStations.add(new Station("SAMARI", "15103"));
        allStations.add(new Station("DRENOVAČKI KIK", "15104"));
        allStations.add(new Station("RAŽANA", "15105"));
        allStations.add(new Station("KOSJERIĆ", "15106"));
        allStations.add(new Station("KALENIĆ", "15107"));
        allStations.add(new Station("SEVOJNO", "15108"));
        allStations.add(new Station("TUBIĆI", "15109"));
        allStations.add(new Station("UZIĆI", "15110"));
        allStations.add(new Station("RASNA", "15111"));
        allStations.add(new Station("LESKOVICE", "15112"));
        allStations.add(new Station("GLUMAC", "15113"));
        allStations.add(new Station("ZLAKUSA", "15114"));
        allStations.add(new Station("OTANJ", "15116"));
        allStations.add(new Station("RAČA", "15118"));
        allStations.add(new Station("POŽEGA", "15150"));
        allStations.add(new Station("UŽICE TERETNA", "15151"));
        allStations.add(new Station("UŽICE", "15153"));
        allStations.add(new Station("BELA REKA", "15201"));
        allStations.add(new Station("BARAJEVO", "15203"));
        allStations.add(new Station("BARAJEVO CENTAR", "15204"));
        allStations.add(new Station("VELIKI BORAK", "15205"));
        allStations.add(new Station("LESKOVAC KOLUBARSKI", "15206"));
        allStations.add(new Station("STEPOJEVAC", "15207"));
        allStations.add(new Station("LAZAREVAC", "15209"));
        allStations.add(new Station("SLOVAC", "15211"));
        allStations.add(new Station("MLAĐEVO", "15212"));
        allStations.add(new Station("DIVCI", "15213"));
        allStations.add(new Station("IVERAK", "15215"));
        allStations.add(new Station("VREOCI", "15250"));
        allStations.add(new Station("VALJEVO", "15251"));
        allStations.add(new Station("LAJKOVAC", "15260"));
        allStations.add(new Station("RIPANJ", "15402"));
        allStations.add(new Station("KLENJE", "15403"));
        allStations.add(new Station("RIPANJ TUNEL", "15404"));
        allStations.add(new Station("RALJA", "15405"));
        allStations.add(new Station("SOPOT KOSMAJSKI", "15406"));
        allStations.add(new Station("VLAŠKO POLJE", "15407"));
        allStations.add(new Station("RIPANJ KOLONIJA", "15408"));
        allStations.add(new Station("MLADENOVAC", "15460"));
        allStations.add(new Station("RESNIK", "15501"));
        allStations.add(new Station("STAPARI", "15701"));
        allStations.add(new Station("SUŠICA", "15702"));
        allStations.add(new Station("BRANEŠCI", "15703"));
        allStations.add(new Station("ZLATIBOR", "15704"));
        allStations.add(new Station("RIBNICA ZLATIBORSKA", "15705"));
        allStations.add(new Station("JABLANICA", "15706"));
        allStations.add(new Station("ŠTRPCI", "15707"));
        allStations.add(new Station("PRIBOJ", "15708"));
        allStations.add(new Station("PRIBOJSKA BANJA", "15709"));
        allStations.add(new Station("BISTRICA NA LIMU", "15710"));
        allStations.add(new Station("PRIJEPOLJE", "15711"));
        allStations.add(new Station("PRIJEPOLJE TERETNA", "15712"));
        allStations.add(new Station("RISTANOVIĆA POLJE", "15716"));
        allStations.add(new Station("TRIPKOVA", "15717"));
        allStations.add(new Station("DŽUROVO", "15718"));
        allStations.add(new Station("POLJICE", "15722"));
        allStations.add(new Station("ZEMUNSKO POLJE", "16001"));
        allStations.add(new Station("ZEMUN", "16002"));
        allStations.add(new Station("NOVI BEOGRAD", "16003"));
        allStations.add(new Station("SEBEŠ", "16006"));
        allStations.add(new Station("OVČA", "16007"));
        allStations.add(new Station("TOŠIN BUNAR", "16012"));
        allStations.add(new Station("PANČEVAČKI MOST", "16013"));
        allStations.add(new Station("PANČEVO STRELIŠTE", "16014"));
        allStations.add(new Station("KRNJAČA", "16015"));
        allStations.add(new Station("KRNJAČA MOST STA", "16016"));
        allStations.add(new Station("BEOGRAD CENTAR", "16052"));
        allStations.add(new Station("KARAĐORĐEV PARK", "16053"));
        allStations.add(new Station("VUKOV SPOMENIK", "16054"));
        allStations.add(new Station("KIJEVO", "16101"));
        allStations.add(new Station("KNEZEVAC", "16102"));
        allStations.add(new Station("RAKOVICA", "16103"));
        allStations.add(new Station("BATAJNICA", "16204"));
        allStations.add(new Station("LOZNICA", "16310"));
        allStations.add(new Station("ZVORNIK", "16317"));
        allStations.add(new Station("ŠABAC", "16350"));
        allStations.add(new Station("NOVA PAZOVA", "16501"));
        allStations.add(new Station("STARA PAZOVA", "16503"));
        allStations.add(new Station("GOLUBINCI", "16505"));
        allStations.add(new Station("PUTINCI", "16506"));
        allStations.add(new Station("KRALJEVCI STAJ", "16507"));
        allStations.add(new Station("SREMSKA MITROVICA", "16509"));
        allStations.add(new Station("MARTINCI", "16511"));
        allStations.add(new Station("KUKUJEVCI-ERDEVIK", "16513"));
        allStations.add(new Station("ŠID", "16516"));
        allStations.add(new Station("RUMA", "16550"));
        allStations.add(new Station("BUĐANOVCI", "16601"));
        allStations.add(new Station("NIKINCI", "16602"));
        allStations.add(new Station("PLATIĆEVO", "16603"));
        allStations.add(new Station("KLENAK", "16604"));
        allStations.add(new Station("INĐIJA", "16801"));
        allStations.add(new Station("BEŠKA", "16802"));
        allStations.add(new Station("SREMSKI KARLOVCI", "16806"));
        allStations.add(new Station("PETROVARADIN", "16807"));
        allStations.add(new Station("NOVI SAD", "16808"));
        allStations.add(new Station("SZENTMIHALYTELEK", "17665"));
        allStations.add(new Station("PANČEVO VAROŠ", "21001"));
        allStations.add(new Station("BANATSKO NOVO SELO", "21002"));
        allStations.add(new Station("VLADIMIROVAC", "21003"));
        allStations.add(new Station("ALIBUNAR", "21004"));
        allStations.add(new Station("BANATSKI KARLOVAC", "21005"));
        allStations.add(new Station("NIKOLINCI", "21006"));
        allStations.add(new Station("ULJMA", "21007"));
        allStations.add(new Station("VLAJKOVAC", "21008"));
        allStations.add(new Station("VRŠAC", "21009"));
        allStations.add(new Station("PANČEVO VOJLOVICA", "21101"));
        allStations.add(new Station("PANČEVO GLAVNA", "22001"));
        allStations.add(new Station("JABUKA", "22002"));
        allStations.add(new Station("KAČAREVO", "22003"));
        allStations.add(new Station("CREPAJA", "22004"));
        allStations.add(new Station("DEBELJAČA", "22005"));
        allStations.add(new Station("KOVAČICA", "22006"));
        allStations.add(new Station("UZDIN", "22201"));
        allStations.add(new Station("TOMAŠEVAC", "22202"));
        allStations.add(new Station("ORLOVAT STAJALIŠTE", "22203"));
        allStations.add(new Station("LUKIĆEVO", "22204"));
        allStations.add(new Station("ZRENJANIN FABRIKA", "22501"));
        allStations.add(new Station("ELEMIR", "22503"));
        allStations.add(new Station("MELENCI", "22504"));
        allStations.add(new Station("KUMANE", "22505"));
        allStations.add(new Station("NOVI BEČEJ", "22506"));
        allStations.add(new Station("BANAT.MILOŠEVO POLJE", "22508"));
        allStations.add(new Station("BANATSKO MILOŠEVO", "22509"));
        allStations.add(new Station("ZRENJANIN", "22550"));
        allStations.add(new Station("BOČAR", "22601"));
        allStations.add(new Station("PADEJ", "22603"));
        allStations.add(new Station("OSTOJIĆEVO", "22604"));
        allStations.add(new Station("ČOKA", "22605"));
        allStations.add(new Station("KIKINDA", "22850"));
        allStations.add(new Station("SUBOTICA", "23450"));
        allStations.add(new Station("HORGOŠ", "23701"));
        allStations.add(new Station("BAČKI VINOGRADI", "23702"));
        allStations.add(new Station("HAJDUKOVO", "23703"));
        allStations.add(new Station("PALIĆ", "23704"));
        allStations.add(new Station("SUBOTICA JAV.SKLADIŠTA", "23706"));
        allStations.add(new Station("SENTA", "23801"));
        allStations.add(new Station("GORNJI BREG", "23802"));
        allStations.add(new Station("BOGARAŠ", "23803"));
        allStations.add(new Station("DOLINE", "23804"));
        allStations.add(new Station("OROM", "23805"));
        allStations.add(new Station("GABRIĆ", "23806"));
        allStations.add(new Station("BIKOVO", "23807"));
        allStations.add(new Station("GAJDOBRA", "24001"));
        allStations.add(new Station("FUTOG", "24003"));
        allStations.add(new Station("PETROVAC-GLOŽAN", "24004"));
        allStations.add(new Station("BAČKI MAGLIĆ", "24005"));
        allStations.add(new Station("SVETOZAR MILETIĆ", "24401"));
        allStations.add(new Station("ALEKSA ŠANTIĆ", "24403"));
        allStations.add(new Station("BAJMOK", "24404"));
        allStations.add(new Station("TAVANKUT", "24406"));
        allStations.add(new Station("PARAGE", "25001"));
        allStations.add(new Station("RATKOVO", "25002"));
        allStations.add(new Station("ODŽACI", "25003"));
        allStations.add(new Station("ODŽACI KALVARIJA", "25401"));
        allStations.add(new Station("KARAVUKOVO", "25402"));
        allStations.add(new Station("BOGOJEVO SELO", "25403"));
        allStations.add(new Station("BOGOJEVO", "25470"));
        allStations.add(new Station("SONTA", "25501"));
        allStations.add(new Station("PRIGREVICA", "25502"));
        allStations.add(new Station("BUKOVAČKI SALAŠI", "25503"));
        allStations.add(new Station("SOMBOR", "25550"));
        allStations.add(new Station("PODGORICA", "31001"));
        allStations.add(new Station("GOLUBOVCI", "31002"));
        allStations.add(new Station("SUTOMORE", "31008"));
        allStations.add(new Station("BAR", "31080"));
        allStations.add(new Station("BIJELO POLJE", "31302"));
        allStations.add(new Station("MOJKOVAC", "31305"));
        allStations.add(new Station("KOLAŠIN", "31307"));
    }
}
